-- Auto-generated by generate-question-import-sql.cjs
START TRANSACTION;

-- categories
INSERT INTO categories (name, slug) VALUES ('React', 'react') ON DUPLICATE KEY UPDATE name = VALUES(name);
INSERT INTO categories (name, slug) VALUES ('TypeScript', 'typescript') ON DUPLICATE KEY UPDATE name = VALUES(name);

-- tags
INSERT INTO tags (name, slug) VALUES ('Hooks', 'hooks') ON DUPLICATE KEY UPDATE name = VALUES(name);
INSERT INTO tags (name, slug) VALUES ('渲染机制', 'u6e32-u67d3-u673a-u5236') ON DUPLICATE KEY UPDATE name = VALUES(name);
INSERT INTO tags (name, slug) VALUES ('类型系统', 'u7c7b-u578b-u7cfb-u7edf') ON DUPLICATE KEY UPDATE name = VALUES(name);
INSERT INTO tags (name, slug) VALUES ('基础', 'u57fa-u7840') ON DUPLICATE KEY UPDATE name = VALUES(name);

-- questions
-- question 1: React 中 useEffect 和 useLayoutEffect 的区别是什么？
INSERT INTO questions (title, content, answer, difficulty, category_id, source_type, source_url, source_name, review_status, published_at) SELECT 'React 中 useEffect 和 useLayoutEffect 的区别是什么？', '请说明两者的执行时机，以及分别适合处理什么问题。', 'useEffect 在浏览器完成绘制后执行，适合副作用与异步逻辑；useLayoutEffect 在 DOM 变更后、浏览器绘制前同步执行，适合读取布局和避免闪烁。', 'medium', c.id, 'imported', NULL, 'manual', 1, NOW() FROM categories c WHERE c.slug = 'react';
SET @question_id = LAST_INSERT_ID();
INSERT IGNORE INTO question_tags (question_id, tag_id) SELECT @question_id, t.id FROM tags t WHERE t.slug = 'hooks';
INSERT IGNORE INTO question_tags (question_id, tag_id) SELECT @question_id, t.id FROM tags t WHERE t.slug = 'u6e32-u67d3-u673a-u5236';

-- question 2: TypeScript 中 unknown 和 any 的区别是什么？
INSERT INTO questions (title, content, answer, difficulty, category_id, source_type, source_url, source_name, review_status, published_at) SELECT 'TypeScript 中 unknown 和 any 的区别是什么？', '请从类型安全、使用限制和推荐场景说明区别。', 'any 会跳过类型检查，任何操作都能通过；unknown 更安全，使用前必须先缩小类型或断言，因此更适合不确定的外部输入。', 'easy', c.id, 'imported', NULL, 'manual', 1, NOW() FROM categories c WHERE c.slug = 'typescript';
SET @question_id = LAST_INSERT_ID();
INSERT IGNORE INTO question_tags (question_id, tag_id) SELECT @question_id, t.id FROM tags t WHERE t.slug = 'u7c7b-u578b-u7cfb-u7edf';
INSERT IGNORE INTO question_tags (question_id, tag_id) SELECT @question_id, t.id FROM tags t WHERE t.slug = 'u57fa-u7840';

COMMIT;
